
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under uploads/versions

backend:
  name: git-gateway
  repo: https://github.com/sites-yari/hotel-is
  branch: master # Branch to update (optional; defaults to master)


collections: #====================| POSTS |===================================================|  
#   - name: "posts"
#     label: "Instruções"
#     folder: "_posts"§
#     create: false
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#     fields:
#       - { label: "Titulo", name: "title", widget: "hidden", default: "read-me" }
#       - { label: "Classe", name: "class", widget: "hidden", default: "" }
#       - { label: "categoria", name: "categoria", widget: "hidden", default: "instrucoes" }
#       - { label: "date", name: "date", widget: "hidden", format: "YYYY-MM-DD hh:mma" }
#       - { label: "READ ME", name: "body", widget: "markdown" }
#     meta: # Meta data fields. Just like fields, but without any preview element
#       - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}



  - name: "data" #|=====================| DATA |====================================================|
    label: "Data"
    editor:
      preview: true
    files:
      #---| INDEX |---
      - name: "front"
        label: "Pagina de Inicial"
        file: "_data/front.yml"
        description: . . .
        fields:
          - label: "PT"
            name: pt
            widget: "object"
            fields:
              - label: "Equipamentos"
                name: index
                widget: "object"
                fields:
                  - { label: "Equipamento 1", name: "opt1", widget: "string" }
                  - { label: "Equipamento 2", name: "opt2", widget: "string" }
                  - { label: "Equipamento 3", name: "opt3", widget: "string" }
                  - { label: "Equipamento 4", name: "opt4", widget: "string" }
                  - { label: "Equipamento 5", name: "opt5", widget: "string" }
                  - { label: "Equipamento 6", name: "opt6", widget: "string" }
                  - { label: "Equipamento 7", name: "opt7", widget: "string" }
                  - { label: "Equipamento 8", name: "opt8", widget: "string" }
                  - { label: "Equipamento 9", name: "opt9", widget: "string" }
                  - { label: "Equipamento 10", name: "opt10", widget: "string" }
                  - { label: "Equipamento 11", name: "opt11", widget: "string" }
                  - { label: "Equipamento 12", name: "opt12", widget: "string" }
                  - { label: "Equipamento 13", name: "opt13", widget: "string" }
                  - { label: "Equipamento 14", name: "opt14", widget: "string" }
                  - { label: "Equipamento 15", name: "opt15", widget: "string" }
                  - { label: "Equipamento 16", name: "opt16", widget: "string" }
                  - { label: "Equipamento 17", name: "opt17", widget: "string" }
                  - { label: "Equipamento 18", name: "opt18", widget: "string" }
                  - { label: "Equipamento 19", name: "opt19", widget: "string" }
          - label: "EN"
            name: en
            widget: "object"
            fields:
              - label: "Equipamentos"
                name: index
                widget: "object"
                fields:
                  - { label: "Equipamento 1", name: "opt1", widget: "string" }
                  - { label: "Equipamento 2", name: "opt2", widget: "string" }
                  - { label: "Equipamento 3", name: "opt3", widget: "string" }
                  - { label: "Equipamento 4", name: "opt4", widget: "string" }
                  - { label: "Equipamento 5", name: "opt5", widget: "string" }
                  - { label: "Equipamento 6", name: "opt6", widget: "string" }
                  - { label: "Equipamento 7", name: "opt7", widget: "string" }
                  - { label: "Equipamento 8", name: "opt8", widget: "string" }
                  - { label: "Equipamento 9", name: "opt9", widget: "string" }
                  - { label: "Equipamento 10", name: "opt10", widget: "string" }
                  - { label: "Equipamento 11", name: "opt11", widget: "string" }
                  - { label: "Equipamento 12", name: "opt12", widget: "string" }
                  - { label: "Equipamento 13", name: "opt13", widget: "string" }
                  - { label: "Equipamento 14", name: "opt14", widget: "string" }
                  - { label: "Equipamento 15", name: "opt15", widget: "string" }
                  - { label: "Equipamento 16", name: "opt16", widget: "string" }
                  - { label: "Equipamento 17", name: "opt17", widget: "string" }
                  - { label: "Equipamento 18", name: "opt18", widget: "string" }
                  - { label: "Equipamento 19", name: "opt19", widget: "string" }    
      #---| Serviços |---
      - name: "servicos"
        label: "Pagina de Serviços"
        file: "_data/servicos.yml"
        description: . . .
        fields:
          - label: "PT"
            name: pt
            widget: "object"
            fields:
              - label: "Sobre"
                name: sobre
                widget: "object"
                fields:
                  - { label: "Projeto 1", name: "projeto1", widget: "string" }
                  - { label: "Descrição 1", name: "acerca1", widget: "string" }
                  - { label: "Projeto 2", name: "projeto2", widget: "string" }
                  - { label: "Descrição 2", name: "acerca2", widget: "string" }
                  - { label: "Projeto 3", name: "projeto3", widget: "string" }
                  - { label: "Descrição 3", name: "acerca3", widget: "string" }
                  - { label: "Projeto 4", name: "projeto4", widget: "string" }
                  - { label: "Descrição 4", name: "acerca4", widget: "string" }
          - label: "EN"
            name: en
            widget: "object"
            fields:
              - label: "Sobre"
                name: sobre
                widget: "object"
                fields:
                  - { label: "Projeto 1", name: "projeto1", widget: "string" }
                  - { label: "Descrição 1", name: "acerca1", widget: "string" }
                  - { label: "Projeto 2", name: "projeto2", widget: "string" }
                  - { label: "Descrição 2", name: "acerca2", widget: "string" }
                  - { label: "Projeto 3", name: "projeto3", widget: "string" }
                  - { label: "Descrição 3", name: "acerca3", widget: "string" }
                  - { label: "Projeto 4", name: "projeto4", widget: "string" }
                  - { label: "Descrição 4", name: "acerca4", widget: "string" }          






